spring:
  datasource:
    username: ${DB_USERNAME:doadmin}
    password: ${DB_PASSWORD:AVNS_lyaRcf1qQoH1oWGX86J}
    url: ${DB_URL:jdbc:postgresql://db-postgresql-webdevs-do-user-17849782-0.i.db.ondigitalocean.com:25060/donatehub}
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:bilmayman}
#    url: ${DB_URL:jdbc:postgresql://localhost:5432/donatehub}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: DonateHub

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

mirpay:
  kassa_id: 1304
  api_key: 0acff03cbd4fca201735b13e4754fb4c

default:
  donation:
    video:
      url: https://videos.pexels.com/video-files/27977624/12279337_1440_2560_60fps.mp4
    audio:
      url: null

click:
  service:
    id: 37162
  merchant:
    id: 28151
  return:
    url: ""

server:
  port: 8050

jwt:
  secret:
    key: ty1fiu23uft12vi3kl123kjkjnkl123njn213ugyuovbj312
  hours: 111

bot:
  token: 7131847164:AAFmhXirKlFAFw7oIERA2YALge8pbg42PwQ
  chatId: 1870689122