name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "DATABASE_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DATABASE_USERNAME_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DATABASE_USERNAME_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "MIRPAY_KASSA_ID=${{ secrets.MIRPAY_KASSA_ID }}" >> $GITHUB_ENV
          echo "MIRPAY_API_KEY=${{ secrets.MIRPAY_API_KEY }}" >> $GITHUB_ENV
          echo "CLICK_SERVICE_ID=${{ secrets.CLICK_SERVICE_ID }}" >> $GITHUB_ENV
          echo "CLICK_MERCHANT_ID=${{ secrets.CLICK_MERCHANT_ID }}" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> $GITHUB_ENV
          echo "BOT_CHAT_ID=${{ secrets.BOT_CHAT_ID }}" >> $GITHUB_ENV
